Repository trace4cats/trace4cats-newrelic, pull requests merged in 2021-07, with the labels that each got.

#6 Update Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#11 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#12 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#13 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#14 Add scala 3
  .github/workflows/ci.yml
  ci-release.sbt
  modules/newrelic-http-exporter/src/main/scala/io/janstenpickle/trace4cats/newrelic/Convert.scala
  project/Dependencies.scala
Labels: enhancement
